project_name: sunset-berlin

before:
  hooks:
    - go mod tidy

builds:
  - id: sunset-berlin
    main: ./
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s"
      - "-w"
      - "-X main.version={{ .Version }}"
      - "-X main.osArch={{ .Os }}/{{ .Arch }}"

archives:
  - id: "sunset-berlin"
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_{{ .Version }}"
    format_overrides:
      - goos: windows
        format: zip
      - goos: darwin
        format: tar.gz
      - goos: linux
        format: tar.gz
    files:
      - "{{ .Os }}-{{ .Arch }}/{{ .ProjectName }}*"


nfpms:
  - maintainer: RehJunior
    description: shows when the sun goes down in Berlin
    homepage: https://github.com/RehJunior/sunset-berlin/
    license: MIT
    formats:
      - deb
      - rpm



furies:
  - # fury.io account.
    # Config is skipped if empty
    account: cyberants
    # Environment variable name to get the push token from.
    # You might want to change it if you have multiple fury configurations for
    # some reason.
    #
    # Default: 'FURY_TOKEN'
    secret_name: FURY_TOKEN
    # Formats to upload.
    # Available options are `deb` and `rpm`.
    #
    # Default: ['deb', 'rpm']
    formats:
      - deb
      - rpm


chocolateys:
  - name: "sunset-berlin"
    ids:
      - sunset-berlin
    owners: RehJunior
    authors: RehJunior
    project_url: https://github.com/RehJunior/sunset-berlin/
    url_template: "https://github.com/RehJunior/sunset-berlin/releases/download/v{{ .Version }}/{{ .ArtifactName }}"
    icon_url: "https://openmoji.org/php/download_asset.php?type=emoji&emoji_hexcode=1F307&emoji_variant=color"
    copyright: Copyright © RehJunior, 2022
    license_url: https://github.com/RehJunior/sunset-berlin/blob/main/LICENSE
    project_source_url: https://github.com/RehJunior/sunset-berlin
    docs_url: https://github.com/RehJunior/sunset-berlin/blob/main/README.md
    bug_tracker_url: https://github.com/RehJunior/sunset-berlin/issues
    tags: "sunset-berlin"
    summary: Shows when the sun goes down in Berlin
    description: |
      {{ .ProjectName }} shows when the sun goes down in Berlin every time that you run.
    release_notes: "https://github.com/RehJunior/sunset-berlin/releases/tag/v{{ .Version }}"
    api_key: '{{ .Env.CHOCOLATEY_API_KEY }}'
      