project_name: sunset-berlin

before:
  hooks:
    - go mod tidy

builds:
  - id: 'sunset-berlin'
    main: ./
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
    ldflags:
      - '-s'
      - '-w'
      - '-X main.version={{ .Version }}'
      - '-X main.osArch={{ .Os }}/{{ .Arch }}'

archives:
  - id: "sunset-berlin"
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_{{ .Version }}'
    format_overrides:
      - goos: windows
        format: zip
      - goos: darwin
        format: tar.gz
      - goos: linux
        format: tar.gz
    files:
      - "{{ .Os }}-{{ .Arch }}/{{ .ProjectName }}*"


chocolateys:
  -
    # Your app's package name.
    # The value may not contain spaces or character that are not valid for a URL.
    # If you want a good separator for words, use '-', not  '.'.
    #
    # Defaults to `ProjectName`.
    name: 'sunset-berlin'

    # IDs of the archives to use.
    # Defaults to empty, which includes all artifacts.
    ids:
      - 'sunset-berlin'

    # Your app's package source url.
    # Default is empty.
    #    package_source_url: https://github.com/faabiosr/chocolatey-packages/tree/main/rand-beer

    # Your app's owner.
    # It basically means your.
    # Defaults empty.
    owners: RehJunior

    # The app's title.
    # A human-friendly title of the package.
    # Defaults to `ProjectName`.
    title: Sunset Berlin

    # Your app's authors (probably you).
    # Defaults are shown below.
    authors: RehJunior

    # Your app's project url.
    # It is a required field.
    project_url: https://github.com/RehJunior/sunset-berlin/

    # Template for the url which is determined by the given Token (github,
    # gitlab or gitea)
    # Default depends on the client.
    url_template: "https://github.com/RehJunior/sunset-berlin/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    # App's icon.
    # Default is empty.
    icon_url: 'https://rawcdn.githack.com/RehJunior/sunset-berlin/ad7fa77314374e3537e80600e26efd745ede9864/icon.png'

    # Your app's copyright details.
    # Default is empty.
    # copyright: 2022 Fabio Ribeiro

    # App's license information url.
    license_url: https://github.com/RehJunior/sunset-berlin/blob/main/LICENSE

    # Your apps's require license acceptance:
    # Specify whether the client must prompt the consumer to accept the package
    # license before installing.
    # Default is false.
    require_license_acceptance: false

    # Your app's source url.
    # Default is empty.
    project_source_url: https://github.com/RehJunior/sunset-berlin

    # Your app's documentation url.
    # Default is empty.
    docs_url: https://github.com/RehJunior/sunset-berlin/blob/main/README.md

    # App's bugtracker url.
    # Default is empty.
    bug_tracker_url: https://github.com/RehJunior/sunset-berlin/issues

    # Your app's tag list.
    # Default is empty.
    tags: "sunset-berlin"

    # Your app's summary:
    summary: Shows when the sun goes down in Berlin 

    # This the description of your chocolatey package.
    # Supports markdown.
    description: |
      {{ .ProjectName }} shows when the sun goes down in Berlin  every time that you run.

    # Your app's release notes.
    # A description of the changes made in this release of the package.
    # Supports markdown. To prevent the need to continually update this field,
    # providing a URL to an external list of Release Notes is perfectly
    # acceptable.
    # Default is empty.
    release_notes: "https://github.com/RehJunior/sunset-berlin/releases/tag/v{{ .Version }}"

    # The api key that should be used to push to the chocolatey repository.
    #
    # WARNING: do not expose your api key in the configuration file!
    api_key: '{{ .Env.CHOCOLATEY_API_KEY }}'

    # The source repository that will push the package to.
    #
    # Defaults are shown below.
    source_repo: "https://push.chocolatey.org/"

    # Setting this will prevent goreleaser to actually try to push the package
    # to chocolatey repository, leaving the responsability of publishing it to
    # the user.
    skip_publish: false

    # GOAMD64 to specify which amd64 version to use if there are multiple
    # versions from the build section.
    # Default is v1.
    goamd64: v1

checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'



